version: "3.9"
services:
  app:
    build: .
    container_name: vidly_app
    ports:
      - 3000:3000
    volumes:
      - .:/app
  # db:
  #   image: "mongo:3-xenial"
  #   container_name: vidly_db
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - vidly:/data/db
volumes:
  vidly:
